const module_permission = {
  project:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  task:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  channel:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  employee:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  department:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  designation:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  domain:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  blog:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  category:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  content:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  activity:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  chat:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  contact:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  my_tasks:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  my_blogs:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  my_profile:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  dashboard:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  },
  notification:{
    read:{
      type:Boolean,
      default:true
    },
    write:{
      type:Boolean,
      default:false
    },
    update:{
      type:Boolean,
      default:false
    },
    delete:{
      type:Boolean,
      default:false
    }
  }
}

 module.exports = module_permission;
